language: python
python:
- 3.8
install:
- pip install poetry==1.0.9
script: skip
before_deploy:
- poetry config pypi-token.pypi $PYPI_TOKEN
deploy:
  provider: script
  script: poetry publish --build
  on:
    tags: true
